### ISSUE TITLE
Scanning IoTdisco QR code can cause crash

### ISSUE THREAD

**Issue by PeterWaher** [Trust-Anchor-Group/NeuroAccessMaui#117]
After scanning a iotdisco QR code (with camera, not entering manually), and then pressing the Connect to Device, it sometimes crashes, sometimes doesn't.

The following stack track was logged at the same time:

```
CurrentDomain_UnhandledException
System.Exception: Not connected to XMPP network.
   at NeuroAccessMaui.Services.Xmpp.XmppService.get_XmppClient()
   at NeuroAccessMaui.Services.Xmpp.XmppService.GetRosterItem(String BareJid)
   at NeuroAccessMaui.UI.Pages.Things.ViewThing.ViewThingViewModel.IsOnline(String BareJid)
   at NeuroAccessMaui.UI.Pages.Things.ViewThing.ViewThingViewModel.CalcThingIsOnline()
   at NeuroAccessMaui.UI.Pages.Things.ViewThing.ViewThingViewModel.<XmppService_ConnectionStateChanged>b__5_0()
   at Android.App.SyncContext.<>c__DisplayClass2_0.<Post>b__0()
   at Java.Lang.Thread.RunnableImplementor.Run()
   at Java.Lang.IRunnableInvoker.n_Run(IntPtr jnienv, IntPtr native__this)
   at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PP_V(_JniMarshal_PP_V callback, IntPtr jnienv, IntPtr klazz)
```

Expected: Before getting XmppClient or sending anything after having used the camera, wait for the connection to complete.

**Comment by berggrenmille** [comment]
#120
